# 1 워크플로의 이름 지정
name: CI/CD

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ feat/deploy ]
  pull_request:
    branches: [ main ] # main 브랜치로의 PR에 대해 실행

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정
    #4 실행스텝지정
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
# 환경변수는 GCP에서 직접 설정
#      - name: Create .env file
#        run: |
#          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
#          echo DB_URL=${{ secrets.DB_URL }} >> .env
#          echo DB_USER=${{ secrets.DB_USER }} >> .env
#          echo JWT_TOKEN=${{ secrets.JWT_TOKEN }} >> .env
#          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > google-credentials.json
#          echo "GOOGLE_APPLICATION_CREDENTIALS=${PWD}/google-credentials.json" >> .env
#          cat .env

      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: root
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}
          OPENAI_API: ${{ secrets.OPENAI_API }}

      # Docker 이미지 빌드 및 Google Container Registry(GCR)에 푸시
      # artifact registry 관리자 IAM role 추가 필요
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Google Container Registry
        uses: docker/login-action@v1
        with:
          registry: asia-northeast3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia-northeast3-docker.pkg.dev/ewhathon-youhahak/youhahak-artifact-registry/notegather:latest
          file: Dockerfile
          context: . # 현재 GitHub Actions의 작업 디렉토리를 컨텍스트로 사용
          build-args: |
            JAR_FILE=build/libs/*.jar

      # Google Cloud Run에 배포
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.5.0
        with:
          service: notegather
          image: asia-northeast3-docker.pkg.dev/ewhathon-youhahak/youhahak-artifact-registry/notegather:latest
          region: asia-northeast3
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}